# Generated by Django 5.2.3 on 2025-06-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topicmainpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='TopicPage',
        ),
        migrations.RenameField(
            model_name='topicmainpage',
            old_name='header_subtitle',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topicmainpage',
            old_name='header_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topicpage',
            old_name='intro',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
