# Generated by Django 5.2.3 on 2025-06-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_blogpage_topicpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicpage',
            name='name',
        ),
    ]
