# Generated by Django 5.2.3 on 2025-06-14 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_background_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_title',
            field=models.CharField(blank=True, help_text="Write a short slogan for the website's Homepage.", max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='Main background image of the Homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
