# Generated by Django 5.2.3 on 2025-06-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_header_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_subtitle',
            field=models.CharField(blank=True, help_text='Write a supporting short text that will sit below the title.', max_length=255),
        ),
    ]
